# Redis instance for rspamd
# Persistence enabled for Bayes classifier tolens
port 0
unixsocket /run/redis/rspamd-permanent/redis.sock
unixsocketperm 0666
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfilename "rspamd-permanent.aof"
dir /srv/redis/rspamd-permanent
maxmemory-policy noeviction
loglevel notice
