# Redis instance for rspamd
# Persistence enabled for Bayes classifier tokens
port 0
unixsocket /run/redis/rspamd-permanent/redis.sock
unixsocketperm 0660
daemonize no
supervised systemd
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfilename "rspamd-permanent.aof"
dir /srv/redis/rspamd-permanent
maxmemory-policy noeviction
loglevel notice
protected-mode yes
